baseURL: 'https://blog.opencloud.io/'
languageCode: 'en-us'
title: 'Zamot Personal Notes'
theme: 'beautifulhugo'

markup:
  goldmark:
    renderer:
      unsafe: true

menu:
  main:
    - name: "About"
      url: "page/about/"
      weight: 3
